# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

filter_similarity_matrix <- function(m, threshold) {
    invisible(.Call('_scgraphs_filter_similarity_matrix', PACKAGE = 'scgraphs', m, threshold))
}

filter_similarity_matrix_by_rank <- function(m, threshold) {
    invisible(.Call('_scgraphs_filter_similarity_matrix_by_rank', PACKAGE = 'scgraphs', m, threshold))
}

layout_forceatlas2Cpp <- function(lay, F_att_orig, mass, nodes_size, edge_list, avg_displ, kgrav, iter, prevent_overlap, fixed, max_displ, stopping_tolerance, barnes_hut) {
    invisible(.Call('_scgraphs_layout_forceatlas2Cpp', PACKAGE = 'scgraphs', lay, F_att_orig, mass, nodes_size, edge_list, avg_displ, kgrav, iter, prevent_overlap, fixed, max_displ, stopping_tolerance, barnes_hut))
}

